CREATE TABLE IF NOT EXISTS chats (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  owner_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  is_private BOOL NOT NULL
);
